import os
import time
from dotenv import load_dotenv
from openai import OpenAI

# ── Load environment variables ────────────────────────────
load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# ── Initialize client ─────────────────────────────────────
client = None
if OPENAI_API_KEY:
    client = OpenAI(api_key=OPENAI_API_KEY)

# ── Constants ─────────────────────────────────────────────
DISCLAIMER = (
    "⚠️ AI Rewrite Disclaimer: This neutral version was generated by GPT-3.5. "
    "While it attempts to remove biased language, it may not perfectly preserve "
    "all nuances of the original article. Always verify facts independently before sharing."
)

SYSTEM_PROMPT = (
    "You are an expert neutral journalism editor with 20 years of experience at an unbiased "
    "news agency. Your job is to rewrite news articles to be completely neutral and factual. "
    "You must: remove emotional language and loaded words, remove political framing and "
    "one-sided perspectives, keep every single fact and piece of information intact, maintain "
    "the same structure and flow as the original, use clear simple factual language, never add "
    "new information or opinions, never remove factual information."
)


def _prepare_text(text: str) -> tuple:
    if not text:
        return "", False

    if len(text) <= 3000:
        return text, False

    truncated = text[:3000]
    last_period = truncated.rfind(".")
    last_exclaim = truncated.rfind("!")
    last_question = truncated.rfind("?")
    last_sentence_end = max(last_period, last_exclaim, last_question)

    if last_sentence_end > 2000:
        truncated = truncated[:last_sentence_end + 1]
    else:
        truncated = truncated[:3000]

    return truncated, True


def rewrite_neutral(text: str) -> dict:
    error_return = {
        "rewritten_text": None,
        "original_length": 0,
        "rewritten_length": 0,
        "was_truncated": False,
        "error": None
    }

    if not OPENAI_API_KEY:
        error_return["error"] = "OpenAI API key not found. Please add OPENAI_API_KEY to your .env file"
        return error_return

    if not text or len(text.strip()) < 10:
        error_return["error"] = "Text too short to rewrite"
        return error_return

    prepared_text, was_truncated = _prepare_text(text)
    original_length = len(text)

    user_prompt = (
        "Please rewrite the following news article in a completely neutral, unbiased, factual tone. "
        "Remove all political framing, emotional language, and loaded words while keeping every fact intact. "
        "Do not add commentary. Do not remove facts.\n\n"
        f"ARTICLE TO REWRITE:\n{prepared_text}\n\nNEUTRAL REWRITE:"
    )

    def call_api():
        return client.chat.completions.create(
            model="gpt-3.5-turbo",
            temperature=0.3,
            max_tokens=1500,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt}
            ]
        )

    # First attempt
    try:
        response = call_api()
        rewritten_text = response.choices[0].message.content.strip()
        return {
            "rewritten_text": rewritten_text,
            "original_length": original_length,
            "rewritten_length": len(rewritten_text),
            "was_truncated": was_truncated,
            "error": None
        }

    except Exception as e:
        error_str = str(e)

        # Rate limit — wait and retry
        if "429" in error_str or "rate_limit" in error_str.lower():
            print("Retrying API call...")
            time.sleep(20)
            try:
                response = call_api()
                rewritten_text = response.choices[0].message.content.strip()
                return {
                    "rewritten_text": rewritten_text,
                    "original_length": original_length,
                    "rewritten_length": len(rewritten_text),
                    "was_truncated": was_truncated,
                    "error": None
                }
            except Exception:
                error_return["error"] = "API rate limit reached. Please wait a moment and try again"
                return error_return

        # Timeout — retry immediately
        elif "timeout" in error_str.lower():
            print("Retrying API call...")
            try:
                response = call_api()
                rewritten_text = response.choices[0].message.content.strip()
                return {
                    "rewritten_text": rewritten_text,
                    "original_length": original_length,
                    "rewritten_length": len(rewritten_text),
                    "was_truncated": was_truncated,
                    "error": None
                }
            except Exception:
                error_return["error"] = "Network error connecting to OpenAI. Please check your internet connection"
                return error_return

        # Invalid API key
        elif "401" in error_str or "invalid_api_key" in error_str.lower():
            error_return["error"] = "Invalid OpenAI API key. Please check your .env file"
            return error_return

        # Network error
        elif "network" in error_str.lower() or "connection" in error_str.lower():
            error_return["error"] = "Network error connecting to OpenAI. Please check your internet connection"
            return error_return

        # Any other error
        else:
            error_return["error"] = f"Rewrite failed: {error_str}"
            return error_return


def estimate_cost(text: str) -> dict:
    if not text:
        return {
            "estimated_tokens": 0,
            "estimated_cost_usd": 0.0,
            "estimated_cost_inr": 0.0
        }

    input_tokens = len(text) // 4
    output_tokens = 1500
    total_tokens = input_tokens + output_tokens

    # GPT-3.5-turbo pricing
    # Input: $0.0005 per 1K tokens
    # Output: $0.0015 per 1K tokens
    input_cost = (input_tokens / 1000) * 0.0005
    output_cost = (output_tokens / 1000) * 0.0015
    total_cost_usd = input_cost + output_cost
    total_cost_inr = total_cost_usd * 84

    return {
        "estimated_tokens": total_tokens,
        "estimated_cost_usd": round(total_cost_usd, 5),
        "estimated_cost_inr": round(total_cost_inr, 3)
    }


if __name__ == "__main__":
    print("\n" + "="*55)
    print("  TESTING LLM REWRITER")
    print("="*55)

    test1_text = """
    The heartless Republican politicians have once again stabbed working Americans 
    in the back by blocking desperately needed minimum wage increases. 
    These corrupt lawmakers, funded by greedy corporate billionaires, continue 
    their ruthless war against the poor while ordinary families struggle to survive. 
    The devastating impact of their cruel policies is destroying lives across America 
    as the radical right pushes its dangerous agenda.
    """

    test2_text = """
    The radical socialist Democrats are pushing their dangerous agenda to destroy 
    America's free market with their reckless spending that will bankrupt the nation. 
    These extreme leftists want to take away your freedoms and hand them to the 
    government while hard working patriotic Americans pay the price. 
    Their catastrophic policies are an attack on everything this great nation stands for.
    """

    tests = [
        {"name": "Test 1 — LEFT leaning", "text": test1_text},
        {"name": "Test 2 — RIGHT leaning", "text": test2_text}
    ]

    all_passed = True

    for test in tests:
        print(f"\n{test['name']}")
        print("-"*55)

        cost = estimate_cost(test["text"])
        print(f"Estimated cost: ${cost['estimated_cost_usd']} USD / ₹{cost['estimated_cost_inr']} INR")

        print(f"\nOriginal text:")
        print(f"  {test['text'].strip()[:150]}...")

        result = rewrite_neutral(test["text"])

        if result["error"]:
            print(f"\nERROR: {result['error']}")
            all_passed = False
        else:
            print(f"\nRewritten neutral text:")
            print(f"  {result['rewritten_text'][:300]}...")
            print(f"\nOriginal length : {result['original_length']} chars")
            print(f"Rewritten length: {result['rewritten_length']} chars")
            print(f"Was truncated   : {result['was_truncated']}")

    print("\n" + "="*55)
    if all_passed:
        print("REWRITER WORKING CORRECTLY")
    else:
        print("SOME TESTS FAILED — check errors above")
    print("="*55)